default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_DB_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("POSTGRES_DB_PORT") { '5432' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

user1: &user1
  username: <%= ENV.fetch("POSTGRES_DB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("POSTGRES_DB_PASSWORD") { '' } %>

user2: &user2
  username: <%= ENV.fetch("POSTGRES_DB_USERNAME_REPLICA") { 'postgres_replica' } %>
  password: <%= ENV.fetch("POSTGRES_DB_PASSWORD_REPLICA") { '' } %>

development:
  balance:
    <<: *default
    <<: *user1
    database: <%= ENV.fetch("POSTGRES_DB") { 'balance_development' } %>
  balance_replica:
    <<: *default
    <<: *user2
    database: <%= ENV.fetch("POSTGRES_DB") { 'balance_development' } %>
    replica: true
test:
  balance:
    <<: *default
    <<: *user1
    database: <%= ENV.fetch("POSTGRES_DB") { 'balance_test' } %>
  balance_replica:
    <<: *default
    <<: *user2
    database: <%= ENV.fetch("POSTGRES_DB") { 'balance_test' } %>
    replica: true
